//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppNTCEcommerce2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Endereco()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int idEndereco { get; set; }
        public int idCliente { get; set; }
        [DisplayName("Endereço Completo")]
        public string nomeEndereco { get; set; }
        [DisplayName("Logradouro")]
        public string logradouroEndereco { get; set; }
        [DisplayName("Número")]
        public string numeroEndereco { get; set; }
        [DisplayName("CEP")]
        public string CEPEndereco { get; set; }
        [DisplayName("Endereço")]
        public string complementoEndereco { get; set; }
        [DisplayName("Cidade")]
        public string cidadeEndereco { get; set; }
        [DisplayName("Pais")]
        public string paisEndereco { get; set; }
        [DisplayName("UF")]
        public string UFEndereco { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
