//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppNTCEcommerce2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.ItemPedido = new HashSet<ItemPedido>();
        }
    
        public int idPedido { get; set; }
        public int idCliente { get; set; }
        public byte idStatus { get; set; }
        public System.DateTime dataPedido { get; set; }
        public byte idTipoPagto { get; set; }
        public Nullable<int> idEndereco { get; set; }
        public byte idAplicacao { get; set; }
    
        public virtual Aplicacao Aplicacao { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Endereco Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
        public virtual StatusPedido StatusPedido { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
    }
}
