

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppNTCEcommerce2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public class Produto
    {

        [Key]
        public int idProduto { get; set; }
        [DisplayName("Produto")]
        public string nomeProduto { get; set; }
        [DisplayName("Descrição")]
        public string descProduto { get; set; }
        [DisplayName("Preço")]
        public decimal precProduto { get; set; }
        [DisplayName("Desconto")]
        public Nullable<decimal> descontoPromocao { get; set; }
        public int idCategoria { get; set; }
        public string ativoProduto { get; set; }
        public Nullable<int> idUsuario { get; set; }
        [DisplayName("Quantidade em Estoque")]
        public Nullable<int> qtdMinEstoque { get; set; }
        [DisplayName(" ")]
        public byte[] imagem { get; set; }
        [DisplayName("Categoria")]
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
