//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppNTCEcommerce2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Produto = new HashSet<Produto>();
        }
    
        public int idUsuario { get; set; }
        [DisplayName ("Login: ")]
        [Required]
        [MaxLength (20, ErrorMessage = "Login excede o tamanho permitido.")]
        public string loginUsuario { get; set; }
        [DisplayName ("Senha:")]
        [Required]
        public string senhaUsuario { get; set; }
        [DisplayName ("Nome: ")]
        public string nomeUsuario { get; set; }
        public string tipoPerfil { get; set; }
        public Nullable<bool> usuarioAtivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}
